FROM continuumio/miniconda3:23.10.0-1

COPY environment.yml .
RUN conda env create

WORKDIR /var/www/livedata

COPY docker-entrypoint-coverage.sh /usr/bin/docker-entrypoint.sh

COPY src/live_data_server app
RUN mkdir ./static

WORKDIR /var/www/livedata/app

RUN echo "[run]\nsource=live_data_server,plots\nparallel=True\nrelative_files=True" > /var/www/livedata/app/.coveragerc

RUN chmod +x /usr/bin/docker-entrypoint.sh
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "livedata", "/usr/bin/docker-entrypoint.sh"]
