name: livedata
channels:
  - conda-forge
dependencies:
  - python=2.7
  - pip
  - postgres=9.5.3
  - pip:
    -Django==1.9.12
    -django-cors-headers==1.3.1
    -psycopg2==2.6.2
    -gunicorn==19.10.0
