name: livedata
channels:
  - conda-forge
dependencies:
  - python=3.12
  - postgresql=16
  - sphinx
  - sphinx_rtd_theme
  - django=4.2
  - django-cors-headers=4.4
  - psycopg=3.2
  - gunicorn
  - pytest
  - build
  - versioningit
  - toml
  - pre-commit
  - coverage
