[project]
name = "live_data_server"
description = "Data server for data plots"
dynamic = ["version"]
requires-python = ">=3.6"
dependencies = [
  # list all runtime dependencies here
]
license = { text = "BSD-3" }

[project.urls]
homepage = "https://livedata-ornl.readthedocs.io" # if no homepage, use repo url

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.hatch.build.targets.wheel]
packages = ["src/live_data_server"]

[tool.black]
line-length = 119

[tool.versioningit.vcs]
method = "git"
default-tag = "0.0.1"

[tool.versioningit.next-version]
method = "minor"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}"
dirty = "{version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+d{build_date:%Y%m%d%H%M}"

[tool.versioningit.write]
file = "src/live_data_server/live_data_server/_version.py"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*", "scripts*", "docs*"]

[tool.pytest.ini_options]
pythonpath = [".", "src", "scripts"]
testpaths = ["tests"]
python_files = ["test*.py"]

[tool.ruff]
line-length = 120
lint.select = [
  "A",
  "ARG",
  "ASYNC",
  "BLE",
  "C90",
  "E",
  "F",
  "I",
  "N",
  "UP032",
  "W",
]

[tool.pixi.workspace]
platforms = ["linux-64"]
channels = [
  "conda-forge",
  "https://prefix.dev/pixi-build-backends",
]
# Required until the build feature becomes stable
preview = ["pixi-build"]

[tool.pixi.dependencies]
python = ">=3.6"
django = "=4.2"
django-cors-headers = "=4.4"
psycopg = "=3.2"
coverage = ">=7"

[tool.pixi.tasks]
test = "python -m pytest tests"

[tool.pixi.environments]
default = { features = [
  "dev",
  "docs",
  "test",
], solve-group = "default" }
docs = { features = ["docs"]}
deploy = { features = ["deploy"]}


[tool.pixi.feature.dev.dependencies]
pre-commit = ">=4.2.0"
versioningit = ">=3.2.0"
ruff = "*"

[tool.pixi.feature.test.dependencies]
pytest = ">=8.4.1"

[tool.pixi.feature.docs.dependencies]
sphinx = ">=8"
sphinx_rtd_theme = ">=3.0.1"

[tool.pixi.feature.docs.pypi-dependencies]
live_data_server = { path = ".", editable = true }

[tool.pixi.feature.deploy.dependencies]
gunicorn = ">=23"
postgresql = "=16"
