# Generated by Django 5.1 on 2024-08-08 18:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datarun",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2027, 8, 8, 18, 55, 41, 999298, tzinfo=datetime.timezone.utc),
                verbose_name="Expires",
            ),
        ),
    ]
