# Generated by Django 4.2.15 on 2024-08-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plots", "0002_datarun_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datarun",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="plotdata",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
