name: Run unit tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ["v*"]

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    env:
      DATABASE_NAME: livedatadb
      DATABASE_USER: livedatauser
      DATABASE_PASS: livedatapass
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      LIVE_PLOT_SECRET_KEY: "1234_live_data_server"
      DJANGO_SUPERUSER_USERNAME: livedatauser
      DJANGO_SUPERUSER_PASSWORD: livedatapass
      COVERAGE_RUN: coverage run -m

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          mamba-version: "*"
          environment-file: environment.yml
          #   These don't seem to be valid options for this action
          #   See: https://github.com/conda-incubator/setup-miniconda
          # cache-environment-key: ${{ runner.os }}-env-${{ hashFiles('**/environment.yml') }}
          # cache-downloads-key: ${{ runner.os }}-downloads-${{ hashFiles('**/environment.yml') }}

      - name: Start docker containers
        run: |
          cp ./config/docker-compose.envlocal.yml docker-compose.yml
          if [[ $(docker compose version 2>/dev/null) != "" ]]; then
              DOCKER_COMPOSE="docker compose"
          elif [[ $(docker-compose version 2>/dev/null) != "" ]]; then
              DOCKER_COMPOSE="docker-compose"
          else
              echo "docker compose or docker-compose is not installed" && exit 1
          fi
          $DOCKER_COMPOSE up --build -d

      - name: Sleep, wait for containers to start up
        run: sleep 30

      - name: Run unit tests
        run: python -m pytest tests/

      - name: Stop the coverage process
        # Stopping the coverage process allows the code coverage to be written to disk
        run: docker exec live_data_server_livedata_1 /bin/bash -c "pkill coverage"

      - name: Copy code coverage out of docker container
        run: docker cp live_data_server_livedata_1:/var/www/livedata/app /tmp/

      - name: Combine and show code coverage
        shell: bash -l {0}
        run: |
          cd /tmp/app
          coverage combine
          coverage xml
          cp coverage.xml $OLDPWD
          coverage report

      - name: Bring down docker containers completely now
        # This will completely remove the containers
        run: docker-compose down

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
