name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
    tags: ['v*']

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      DATABASE_NAME: livedatadb
      DATABASE_USER: livedatauser
      DATABASE_PASS: livedatapass
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      LIVE_PLOT_SECRET_KEY: "1234_live_data_server"
      DJANGO_SUPERUSER_USERNAME: livedatauser
      DJANGO_SUPERUSER_PASSWORD: livedatapass
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          channels: conda-forge,defaults
          mamba-version: "*"
          environment-file: environment.yml
          cache-environment-key: ${{ runner.os }}-env-${{ hashFiles('**/environment.yml') }}
          cache-downloads-key: ${{ runner.os }}-downloads-${{ hashFiles('**/environment.yml') }}
      - name: Start docker containers
        run: |
          cp ./config/docker-compose.envlocal.yml docker-compose.yml
          docker compose up --build -d
      - name: Sleep, wait for containers to start up
        run: sleep 30
      - name: Run unit tests
        run: python -m pytest tests/
