name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
    tags: ['v*']

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          mamba-version: "*"
          environment-file: environment.yml
          cache-environment-key: ${{ runner.os }}-env-${{ hashFiles('**/environment.yml') }}
          cache-downloads-key: ${{ runner.os }}-downloads-${{ hashFiles('**/environment.yml') }}
      - name: Start docker containers
        run: |
          cp ./config/docker-compose.envlocal.yml docker-compose.yml
          docker compose up --build
        env:
          DATABASE_NAME: livedatadb
          DATABASE_USER: livedatauser
          DATABASE_PASS: livedatapass
          DATABASE_HOST: db
          DATABASE_PORT: 5432
          LIVE_PLOT_SECRET_KEY: "live_data_server_47352"
          DJANGO_SUPERUSER_USERNAME: ldsuser
          DJANGO_SUPERUSER_PASSWORD: ldspass
      - name: Sleep, wait for containers to start up
        run: sleep 20
      - name: Run unit tests
        run: |
          echo "running unit tests"
          export DJANGO_SUPERUSER_USERNAME=ldsuser DJANGO_SUPERUSER_PASSWORD=ldspass
          python -m pytest --cov=src --cov-report=xml --cov-report=term-missing tests/
        env:
          LIVE_PLOT_SECRET_KEY: "live_data_server_47352"
          DJANGO_SUPERUSER_USERNAME: ldsuser
          DJANGO_SUPERUSER_PASSWORD: ldspass
#      - name: upload coverage to codecov
#        uses: codecov/codecov-action@v4
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
