name: Run unit tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ["v*"]

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: livedatadb
      DATABASE_USER: livedatauser
      DATABASE_PASS: livedatapass
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      LIVE_PLOT_SECRET_KEY: "1234_live_data_server"
      DJANGO_SUPERUSER_USERNAME: livedatauser
      DJANGO_SUPERUSER_PASSWORD: livedatapass
      COVERAGE_RUN: coverage run -m

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.10.2

      - name: Start docker containers
        run: |
          cp ./deploy/docker-compose.envlocal.yml docker-compose.yml
          docker compose up --build -d

      - name: Sleep, wait for containers to start up
        run: sleep 30

      - name: Run unit tests
        run: pixi run test

      - name: Stop the coverage process
        # Stopping the coverage process allows the code coverage to be written to disk
        run: docker exec live_data_server-django-1 /bin/bash -c "pkill coverage"

      - name: Copy code coverage out of docker container
        run: docker cp live_data_server-django-1:/var/www/livedata/app /tmp/

      - name: Combine and show code coverage
        run: |
          pixi run coverage combine --data-file=/tmp/app/.coverage
          cp /tmp/app/.coverage src
          cd src
          pixi run coverage xml
          pixi run coverage report

      - name: Bring down docker containers completely now
        # This will completely remove the containers
        run: docker compose down

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
